### PR TITLE
Created a SignUp page Project

### PR DESCRIPTION
**Pull request by carlosprietobarron**
This is the full project with all the required features.

Created Project layout.

Created and styled the header section.
Created Form Section with input elements.
Styled Form Section.
Created Footer Section with legal anchors.
Styled Footer Section.

### CODE REVIEW

**Comment by euqueme** [comment]
<h2>Pull Request under the review by Maria Eugenia Quemé P. (TSE)</h2>

**Comment by euqueme** [comment]
> ## Pull Request under the review by Maria Eugenia Quemé P. (TSE)
# Hello @carlosprietobarron and @xtrmdarc :woman_technologist: 

### Good job! everything looks nice and it feels like the original :art: also Great job creating a descriptive pull request and descriptive commits :clap: just a couple of things to work on before we can give you the approval:

- [ ] Validate your HTML markup with validator (as described [here](https://github.com/microverseinc/linters-config/tree/master/html_validator)).

[OPTIONAL] You could improve the readme file a bit, by either make the long URL links [shorter](https://tiny.cc/) or have descriptive links like the one you have for the MIT license

## That's it. Please :pray: correct these changes and submit back for a code review when you are done :rocket:

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Hi Team,
## Great  work, Congratulation :+1: 
You did all changes required previously. Go ahead and merge to master
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
